server:
  port : 8399

# Oracle Connect
spring: 
  devtools: 
    livereload:
      enabled: true
  # File Size
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
   url: jdbc:oracle:thin:@localhost:1521/xe
   username: choongang
   password: tiger
   driver-class-name: oracle.jdbc.driver.OracleDriver
   
   # Jpa Setting  
  jpa: 
    hibernate: 
    
      ddl-auto: update  # none   update    create
    properties:
      hibernate:
        default_batch_fetch_size : 500 
#        show_sql: true         # System.out 에 하이버네이트 실행 SQL
#        format_sql: true
#        highlight_sql: true
  
  # view Resolver
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  
  # gmail Transfer 
  mail:
    host: smtp.gmail.com
    port: 587
    username: leoteemo82@gmail.com
    password: hrwavzoccvtkuydd 
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true  
  # jackson
  jackson:
      serialization:
        fail-on-empty-beans: false
        
# Mybatis
mybatis:
  config-location: classpath:configuration.xml
  mapper-locations: classpath:mappers/*.xml

  
  
   
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace      # logger를 통해 하이버네이트 실행 SQL
# jwt secretKey
jwt:
  secret: 64+Z7ZW066y86rO867Cx65GQ7IKw7J2066eI66W06rOg64uz64+E66Gd      